## Working base image (non-tini)
## date tag is correct for 'intel-nuc'
FROM resin/%%RESIN_MACHINE_NAME%%-debian:slim-20170601

# # Upstream works too


# # Non-working base image (tini)

COPY start.sh ./

CMD ["bash", "start.sh"]
