## Working base image (non-tini)
#FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie-20170603

# Upstream works too
#FROM debian:jessie

## Non-working base image (tini)
## date tag is correct for 'intel-nuc'
FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie-20170801

COPY start.sh ./

CMD ["bash", "start.sh"]
